#!/usr/bin/env python3
"""Generate plugins/emoji/src/table.rs from the gemoji database.
Run once; the table is committed."""

import json
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "plugins" / "emoji" / "src" / "table.rs"


def main():
    data = json.loads(urllib.request.urlopen(URL).read())
    rows = []
    for entry in data:
        emoji = entry.get("emoji")
        if not emoji:
            continue
        for alias in entry.get("aliases", []):
            rows.append((alias, emoji))
    rows.sort()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        f.write("//! GENERATED by scripts/gen_emoji_table.py - do not edit.\n")
        f.write("pub static TABLE: &[(&str, &str)] = &[\n")
        for alias, emoji in rows:
            f.write("    ({}, {}),\n".format(json.dumps(alias, ensure_ascii=False), json.dumps(emoji, ensure_ascii=False)))
        f.write("];\n")
    print("wrote {} ({} shortcodes)".format(OUT, len(rows)))


if __name__ == "__main__":
    main()
