#!/usr/bin/env python3
"""Vendor the Seti UI icon pack (MIT) and generate src/seti.rs.

Downloads all icon SVGs + LICENSE from jesseweed/seti-ui@master into
assets/icons/seti/, parses styles/components/icons/mapping.less, and
emits a static Rust lookup module. Rerun to refresh the vendor drop;
tests live in src/seti_tests.rs and survive regeneration.

Matching semantics (deliberately case-insensitive, unlike raw CSS):
  exact file name -> substring (icon-partial) -> longest dotted suffix
  (icon-set ".ext") -> default. Within each class, later mapping.less
  rules win (CSS document order).
"""

import json
import re
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/jesseweed/seti-ui/master"
API_ICONS = "https://api.github.com/repos/jesseweed/seti-ui/contents/icons"
ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "icons" / "seti"
OUT = ROOT / "src" / "seti.rs"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "supermd-vendor"})
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)

    icons = [
        item["name"]
        for item in json.loads(fetch(API_ICONS))
        if item["name"].endswith(".svg")
    ]
    print(f"downloading {len(icons)} icons…")
    for name in icons:
        target = ASSETS / name
        if not target.exists():
            target.write_bytes(fetch(f"{RAW}/icons/{name}"))
    (ASSETS / "LICENSE").write_bytes(fetch(f"{RAW}/LICENSE.md"))
    icon_names = {n[:-4] for n in icons}

    mapping = fetch(f"{RAW}/styles/components/icons/mapping.less").decode()
    rule_re = re.compile(
        r'\.icon-(set|partial)\("([^"]+)",\s*"([^"]+)",\s*@([\w-]+)\)'
    )
    full_rules, partial_rules, ext_rules = [], [], []
    colors = set()
    dropped = []
    for kind, matcher, icon, color in rule_re.findall(mapping):
        if icon not in icon_names:
            dropped.append((matcher, icon))
            icon = "default"
        color_variant = "".join(p.capitalize() for p in color.split("-"))
        colors.add(color_variant)
        matcher = matcher.lower()
        if kind == "partial":
            partial_rules.append((matcher, icon, color_variant))
        elif matcher.startswith("."):
            ext_rules.append((matcher, icon, color_variant))
        else:
            full_rules.append((matcher, icon, color_variant))
    if dropped:
        print(f"note: {len(dropped)} rules referenced missing icons -> default: {dropped}")

    # Longest suffix first; later document order wins among equal lengths.
    ext_sorted = sorted(
        enumerate(ext_rules), key=lambda p: (-len(p[1][0]), -p[0])
    )
    ext_rules = [rule for _, rule in ext_sorted]
    # Later rules win for exact/partial: reverse once here.
    full_rules.reverse()
    partial_rules.reverse()

    def rule_lines(rules):
        return "\n".join(
            f'    ("{m}", "{i}", SetiColor::{c}),' for m, i, c in rules
        )

    color_variants = "\n".join(f"    {c}," for c in sorted(colors))
    icon_lines = "\n".join(
        f'    ("{n[:-4]}", include_bytes!("../assets/icons/seti/{n}").as_slice()),'
        for n in sorted(icons)
    )

    OUT.write_text(f'''//! GENERATED by scripts/vendor_seti.py — do not edit by hand.
//! Icon art: Seti UI (MIT), see assets/icons/seti/LICENSE.
//! Tests: src/seti_tests.rs (hand-written, survives regeneration).

/// Embedded Seti SVGs, keyed by icon name.
pub const ICONS: &[(&str, &[u8])] = &[
{icon_lines}
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SetiColor {{
{color_variants}
}}

/// Exact-filename rules (highest precedence; already priority-ordered).
const FULL_RULES: &[(&str, &str, SetiColor)] = &[
{rule_lines(full_rules)}
];

/// Filename-substring rules (priority-ordered).
const PARTIAL_RULES: &[(&str, &str, SetiColor)] = &[
{rule_lines(partial_rules)}
];

/// Dotted-suffix rules, longest suffix first.
const EXT_RULES: &[(&str, &str, SetiColor)] = &[
{rule_lines(ext_rules)}
];

pub const DEFAULT_ICON: (&str, SetiColor) = ("default", SetiColor::White);

/// Icon + color for a file name, Seti precedence, case-insensitive.
pub fn icon_for(file_name: &str) -> (&'static str, SetiColor) {{
    let lower = file_name.to_ascii_lowercase();
    for (name, icon, color) in FULL_RULES {{
        if lower == *name {{
            return (icon, *color);
        }}
    }}
    for (part, icon, color) in PARTIAL_RULES {{
        if lower.contains(part) {{
            return (icon, *color);
        }}
    }}
    for (suffix, icon, color) in EXT_RULES {{
        if lower.ends_with(suffix) {{
            return (icon, *color);
        }}
    }}
    DEFAULT_ICON
}}

#[cfg(test)]
pub const ALL_RULES_FOR_TEST: &[(&str, &str, SetiColor)] = &[
{rule_lines(full_rules + partial_rules + ext_rules)}
];
''')
    print(
        f"generated src/seti.rs: {len(full_rules)} exact, "
        f"{len(partial_rules)} partial, {len(ext_rules)} suffix rules, "
        f"{len(icons)} icons, {len(colors)} colors"
    )


if __name__ == "__main__":
    main()
