//! WebAssembly extension host: manifest discovery under
//! ~/.supermd/plugins/, wasmtime component instances, and the
//! capability contract (Phase 1: pure functions only). Plugin
//! failures are data, never crashes.

use std::path::{Path, PathBuf};

#[derive(Clone, Debug, serde::Deserialize)]
pub struct CommandInfo {
    pub id: String,
    pub title: String,
}

#[derive(Clone, Debug, serde::Deserialize)]
pub struct InlineRule {
    pub id: String,
    pub pattern: String,
}

#[derive(Clone, Debug, serde::Deserialize)]
pub struct DecorationRule {
    pub pattern: String,
    /// accent | muted | strong | highlight
    pub style: String,
}

#[derive(Clone, Debug)]
pub struct PluginMeta {
    pub name: String,
    pub version: String,
    pub fences: Vec<String>,
    pub commands: Vec<CommandInfo>,
    pub inline: Vec<InlineRule>,
    pub decorations: Vec<DecorationRule>,
    pub formats: bool,
    pub paste: bool,
    pub capabilities: Vec<String>,
    pub dir: PathBuf,
}

#[derive(serde::Deserialize)]
#[serde(deny_unknown_fields)]
struct ManifestFile {
    name: String,
    version: String,
    #[serde(default)]
    description: Option<String>,
    #[serde(default)]
    authors: Option<Vec<String>>,
    #[serde(default)]
    fences: Vec<String>,
    #[serde(default)]
    commands: Vec<CommandInfo>,
    #[serde(default)]
    inline: Vec<InlineRule>,
    #[serde(default)]
    decorations: Vec<DecorationRule>,
    #[serde(default)]
    formats: bool,
    #[serde(default)]
    paste: bool,
    /// Only "workspace-read" is understood; anything else is rejected
    /// so old builds give a clear error for newer manifests.
    #[serde(default)]
    capabilities: Vec<String>,
}

pub fn parse_manifest(dir: &Path, toml_src: &str) -> Result<PluginMeta, String> {
    let file: ManifestFile = toml::from_str(toml_src).map_err(|e| e.to_string())?;
    for cap in &file.capabilities {
        if cap != "workspace-read" {
            return Err(format!(
                "manifest declares capability `{cap}`, which this SuperMD version \
                 does not support (known: workspace-read)"
            ));
        }
    }
    for rule in file.inline.iter().map(|r| &r.pattern).chain(
        file.decorations.iter().map(|r| &r.pattern),
    ) {
        regex::Regex::new(rule).map_err(|e| format!("invalid pattern regex: {e}"))?;
    }
    for d in &file.decorations {
        if !matches!(d.style.as_str(), "accent" | "muted" | "strong" | "highlight") {
            return Err(format!("unknown decoration style `{}`", d.style));
        }
    }
    let _ = (file.description, file.authors);
    Ok(PluginMeta {
        name: file.name,
        version: file.version,
        fences: file.fences,
        commands: file.commands,
        inline: file.inline,
        decorations: file.decorations,
        formats: file.formats,
        paste: file.paste,
        capabilities: file.capabilities,
        dir: dir.to_path_buf(),
    })
}

/// Scan a plugins directory: each subdir needs plugin.toml + plugin.wasm.
/// Returns loaded metas and per-directory failures (never fatal).
pub fn discover(plugins_dir: &Path) -> (Vec<PluginMeta>, Vec<(PathBuf, String)>) {
    let mut loaded = Vec::new();
    let mut failures = Vec::new();
    let entries = match std::fs::read_dir(plugins_dir) {
        Ok(e) => e,
        Err(_) => return (loaded, failures), // no dir yet: nothing installed
    };
    for entry in entries.flatten() {
        let dir = entry.path();
        if !dir.is_dir() {
            continue;
        }
        let manifest_path = dir.join("plugin.toml");
        if !manifest_path.exists() {
            continue; // stray dir, not a plugin
        }
        let result = std::fs::read_to_string(&manifest_path)
            .map_err(|e| e.to_string())
            .and_then(|src| parse_manifest(&dir, &src))
            .and_then(|meta| {
                if dir.join("plugin.wasm").exists() {
                    Ok(meta)
                } else {
                    Err("plugin.wasm missing".to_string())
                }
            });
        match result {
            Ok(meta) => loaded.push(meta),
            Err(e) => failures.push((dir, e)),
        }
    }
    loaded.sort_by(|a, b| a.name.cmp(&b.name));
    (loaded, failures)
}

// ── wasmtime host ──────────────────────────────────────────────────────

wasmtime::component::bindgen!({
    path: "plugins/wit/extension.wit",
    world: "extension",
});

/// 0.2 bindings live in their own module; 0.1 plugins keep working
/// through the fallback in `with_instance`.
mod v2 {
    wasmtime::component::bindgen!({
        path: "plugins/wit-v2/extension.wit",
        world: "extension",
    });
}

use supermd::extension::types as wit_types;

// `CommandOutput` and the other WIT types are generated by bindgen!
// above and re-used directly (variants: ReplaceDocument,
// ReplaceSelection, InsertAtCursor).

/// How long a single plugin call may run before the epoch deadline
/// interrupts it (epoch ticks every 500ms; 4 ticks ≈ 2s).
const EPOCH_TICK_MS: u64 = 500;
const CALL_DEADLINE_TICKS: u64 = 4;

/// Per-store state: WASI with ZERO grants — no preopened dirs, no
/// env, no args, no network. Only stderr is inherited so plugin
/// panics are debuggable. This is the whole Phase 1 capability
/// surface.
struct HostState {
    ctx: wasmtime_wasi::WasiCtx,
    table: wasmtime_wasi::ResourceTable,
}

impl wasmtime_wasi::WasiView for HostState {
    fn ctx(&mut self) -> wasmtime_wasi::WasiCtxView<'_> {
        wasmtime_wasi::WasiCtxView { ctx: &mut self.ctx, table: &mut self.table }
    }
}

fn zero_grant_state() -> HostState {
    HostState {
        ctx: wasmtime_wasi::WasiCtxBuilder::new().inherit_stderr().build(),
        table: wasmtime_wasi::ResourceTable::new(),
    }
}

enum Bound {
    V1(wasmtime::Store<HostState>, Extension),
    V2(wasmtime::Store<HostState>, v2::Extension),
}

struct LoadedPlugin {
    meta: PluginMeta,
    component: wasmtime::component::Component,
    /// Instantiated lazily; dropped after a trap so the next call
    /// gets a fresh store.
    instance: Option<Bound>,
}

pub struct ExtensionHost {
    engine: wasmtime::Engine,
    plugins: Vec<LoadedPlugin>,
    failures: Vec<(PathBuf, String)>,
}

impl ExtensionHost {
    pub fn load(plugins_dir: &Path) -> Self {
        let mut config = wasmtime::Config::new();
        config.epoch_interruption(true);
        let engine = wasmtime::Engine::new(&config).expect("wasmtime engine");
        // Tick the epoch forever; deadlines are per-call offsets.
        {
            let engine = engine.clone();
            std::thread::Builder::new()
                .name("supermd-wasm-epoch".into())
                .spawn(move || loop {
                    std::thread::sleep(std::time::Duration::from_millis(EPOCH_TICK_MS));
                    engine.increment_epoch();
                })
                .expect("epoch thread");
        }

        let (metas, mut failures) = discover(plugins_dir);
        let mut plugins = Vec::new();
        for meta in metas {
            match wasmtime::component::Component::from_file(&engine, meta.dir.join("plugin.wasm"))
            {
                Ok(component) => {
                    plugins.push(LoadedPlugin { meta, component, instance: None })
                }
                Err(e) => failures.push((meta.dir.clone(), format!("compile: {e:#}"))),
            }
        }
        Self { engine, plugins, failures }
    }

    pub fn plugins(&self) -> Vec<PluginMeta> {
        self.plugins.iter().map(|p| p.meta.clone()).collect()
    }

    pub fn failures(&self) -> &[(PathBuf, String)] {
        &self.failures
    }

    fn ensure_bound(&mut self, plugin: &str) -> Result<&mut Bound, String> {
        let Some(slot) = self.plugins.iter_mut().find(|p| p.meta.name == plugin) else {
            return Err(format!("no such plugin '{plugin}'"));
        };
        if slot.instance.is_none() {
            let mut store = wasmtime::Store::new(&self.engine, zero_grant_state());
            store.set_epoch_deadline(CALL_DEADLINE_TICKS);
            let mut linker = wasmtime::component::Linker::new(&self.engine);
            // wasip2 std needs core WASI interfaces even for pure
            // code; the zero-grant ctx keeps the capability surface
            // empty (no fs, no env, no net).
            wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
                .map_err(|e| format!("wasi link: {e:#}"))?;
            // Try 0.2 first, fall back to 0.1.
            match v2::Extension::instantiate(&mut store, &slot.component, &linker) {
                Ok(instance) => slot.instance = Some(Bound::V2(store, instance)),
                Err(_) => {
                    let mut store = wasmtime::Store::new(&self.engine, zero_grant_state());
                    store.set_epoch_deadline(CALL_DEADLINE_TICKS);
                    let instance =
                        Extension::instantiate(&mut store, &slot.component, &linker)
                            .map_err(|e| format!("link: {e:#}"))?;
                    slot.instance = Some(Bound::V1(store, instance));
                }
            }
        }
        Ok(slot.instance.as_mut().expect("just instantiated"))
    }

    fn poison(&mut self, plugin: &str) {
        if let Some(slot) = self.plugins.iter_mut().find(|p| p.meta.name == plugin) {
            slot.instance = None;
        }
    }

    fn with_instance<R>(
        &mut self,
        plugin: &str,
        call: impl FnOnce(&mut Bound) -> wasmtime::Result<R>,
    ) -> Result<R, String> {
        let bound = self.ensure_bound(plugin)?;
        match bound {
            Bound::V1(store, _) => store.set_epoch_deadline(CALL_DEADLINE_TICKS),
            Bound::V2(store, _) => store.set_epoch_deadline(CALL_DEADLINE_TICKS),
        }
        match call(bound) {
            Ok(v) => Ok(v),
            Err(e) => {
                // Trap or deadline: poison-drop the instance.
                self.poison(plugin);
                Err(format!("{e:#}"))
            }
        }
    }

    /// Blocking; call from the background executor only.
    pub fn render_block(
        &mut self,
        plugin: &str,
        lang: &str,
        source: &str,
        theme: &crate::diagram::DiagramTheme,
    ) -> Result<String, String> {
        let wit_theme = wit_types::Theme {
            background: theme.background.clone(),
            surface: theme.surface.clone(),
            primary: theme.primary.clone(),
            text: theme.text.clone(),
            muted: theme.muted.clone(),
            border: theme.border.clone(),
            font_body: theme.font_body.clone(),
            dark: theme.dark,
        };
        self.with_instance(plugin, |bound| match bound {
            Bound::V1(store, i) => i.call_render_block(store, lang, source, &wit_theme),
            Bound::V2(store, i) => {
                let t2 = v2::supermd::extension::types::Theme {
                    background: wit_theme.background.clone(),
                    surface: wit_theme.surface.clone(),
                    primary: wit_theme.primary.clone(),
                    text: wit_theme.text.clone(),
                    muted: wit_theme.muted.clone(),
                    border: wit_theme.border.clone(),
                    font_body: wit_theme.font_body.clone(),
                    dark: wit_theme.dark,
                };
                i.call_render_block(store, lang, source, &t2)
            }
        })?
        .map_err(|e| e)
    }

    /// Blocking; call from the background executor only.
    pub fn run_command(
        &mut self,
        plugin: &str,
        id: &str,
        document: &str,
        selection: std::ops::Range<usize>,
    ) -> Result<CommandOutput, String> {
        let input = wit_types::CommandInput {
            document: document.to_string(),
            selection_start: selection.start.min(u32::MAX as usize) as u32,
            selection_end: selection.end.min(u32::MAX as usize) as u32,
        };
        let out = self.with_instance(plugin, |bound| match bound {
            Bound::V1(store, i) => i.call_run_command(store, id, &input),
            Bound::V2(store, i) => {
                let in2 = v2::supermd::extension::types::CommandInput {
                    document: input.document.clone(),
                    selection_start: input.selection_start,
                    selection_end: input.selection_end,
                };
                i.call_run_command(store, id, &in2).map(|r| {
                    r.map(|o| {
                        use v2::supermd::extension::types::CommandOutput as O2;
                        match o {
                            O2::ReplaceDocument(s) => CommandOutput::ReplaceDocument(s),
                            O2::ReplaceSelection(s) => CommandOutput::ReplaceSelection(s),
                            O2::InsertAtCursor(s) => CommandOutput::InsertAtCursor(s),
                        }
                    })
                })
            }
        })?;
        out.map_err(|e| e)
    }

    /// 0.2-only surfaces; 0.1 plugins get a readable error.
    pub fn render_inline(
        &mut self,
        plugin: &str,
        pattern_id: &str,
        matched: &str,
    ) -> Result<String, String> {
        self.with_instance(plugin, |bound| match bound {
            Bound::V1(..) => Ok(Err("requires a 0.2 plugin".to_string())),
            Bound::V2(store, i) => i.call_render_inline(store, pattern_id, matched),
        })?
        .map_err(|e| e)
    }

    pub fn format_document(&mut self, plugin: &str, document: &str) -> Result<String, String> {
        self.with_instance(plugin, |bound| match bound {
            Bound::V1(..) => Ok(Err("requires a 0.2 plugin".to_string())),
            Bound::V2(store, i) => i.call_format_document(store, document),
        })?
        .map_err(|e| e)
    }

    pub fn process_paste(
        &mut self,
        plugin: &str,
        text: &str,
    ) -> Result<Option<String>, String> {
        self.with_instance(plugin, |bound| match bound {
            Bound::V1(..) => Ok(Err("requires a 0.2 plugin".to_string())),
            Bound::V2(store, i) => i.call_process_paste(store, text),
        })?
        .map_err(|e| e)
    }
}

/// Global handle; plugin calls lock briefly on the background executor.
pub struct ExtensionState(pub std::sync::Arc<std::sync::Mutex<ExtensionHost>>);

impl gpui::Global for ExtensionState {}

/// Snapshot of (plugin, version, claimed fences) for pure discovery
/// contexts (projection runs without cx access).
static FENCE_TABLE: std::sync::OnceLock<Vec<(String, String, Vec<String>)>> =
    std::sync::OnceLock::new();

pub fn set_fence_table(table: Vec<(String, String, Vec<String>)>) {
    let _ = FENCE_TABLE.set(table);
}

pub fn fence_table() -> &'static [(String, String, Vec<String>)] {
    FENCE_TABLE.get().map(|v| v.as_slice()).unwrap_or(&[])
}

#[cfg(test)]
mod host_tests {
    use super::*;

    fn fixtures_dir() -> Option<PathBuf> {
        let d = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/plugins");
        d.join("echo/plugin.wasm").exists().then_some(d)
    }

    #[test]
    fn echo_renderer_roundtrips() {
        let Some(dir) = fixtures_dir() else {
            eprintln!("SKIP: fixtures not built (scripts/build_plugins.sh --fixtures)");
            return;
        };
        let mut host = ExtensionHost::load(&dir);
        assert!(host.failures().is_empty(), "{:?}", host.failures());
        let svg = host
            .render_block(
                "echo",
                "echo-fixture",
                "hello",
                &crate::diagram::DiagramTheme::default_light(),
            )
            .unwrap();
        assert!(svg.contains("echo-fixture:hello"), "{svg}");
    }

    #[test]
    fn echo_command_roundtrips() {
        let Some(dir) = fixtures_dir() else { eprintln!("SKIP"); return; };
        let mut host = ExtensionHost::load(&dir);
        let out = host.run_command("echo", "echo.run", "doc", 0..0).unwrap();
        match out {
            CommandOutput::InsertAtCursor(s) => assert_eq!(s, "echo:echo.run"),
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn panicking_plugin_returns_err_and_recovers() {
        let Some(dir) = fixtures_dir() else { eprintln!("SKIP"); return; };
        let mut host = ExtensionHost::load(&dir);
        let theme = crate::diagram::DiagramTheme::default_light();
        assert!(host.render_block("panic", "x", "y", &theme).is_err());
        assert!(host.render_block("echo", "l", "s", &theme).is_ok());
    }

    #[test]
    fn hanging_plugin_hits_deadline() {
        let Some(dir) = fixtures_dir() else { eprintln!("SKIP"); return; };
        let mut host = ExtensionHost::load(&dir);
        let theme = crate::diagram::DiagramTheme::default_light();
        let t0 = std::time::Instant::now();
        assert!(host.render_block("hang", "x", "y", &theme).is_err());
        assert!(t0.elapsed() < std::time::Duration::from_secs(10));
        // and the host recovers afterward
        assert!(host.render_block("echo", "l", "s", &theme).is_ok());
    }

    #[test]
    fn v2_surfaces_roundtrip_and_v1_gets_readable_error() {
        let Some(dir) = fixtures_dir() else { eprintln!("SKIP"); return; };
        let mut host = ExtensionHost::load(&dir);
        assert_eq!(host.render_inline("echo", "e", ":x:").unwrap(), "[e::x:]");
        assert_eq!(host.format_document("echo", "abc").unwrap(), "ABC");
        assert_eq!(host.process_paste("echo", "ab").unwrap(), Some("ba".to_string()));
        // panic fixture stayed on 0.1: new surfaces err readably,
        // old surfaces still trap-recover.
        let e = host.render_inline("panic", "e", "x").unwrap_err();
        assert!(e.contains("0.2"), "{e}");
    }

    #[test]
    fn unknown_plugin_is_an_error() {
        let dir = tempfile::tempdir().unwrap();
        let mut host = ExtensionHost::load(dir.path());
        assert!(host
            .render_block("ghost", "x", "y", &crate::diagram::DiagramTheme::default_light())
            .is_err());
    }
}

#[cfg(test)]
mod manifest_tests {
    use super::*;

    #[test]
    fn manifest_parses_contributions() {
        let m = parse_manifest(
            Path::new("/p/dot"),
            r#"
name = "dot"
version = "0.1.0"
fences = ["dot", "graphviz"]
[[commands]]
id = "dot.about"
title = "About Dot"
"#,
        )
        .unwrap();
        assert_eq!(m.name, "dot");
        assert_eq!(m.fences, ["dot", "graphviz"]);
        assert_eq!(m.commands[0].id, "dot.about");
        assert_eq!(m.commands[0].title, "About Dot");
    }

    #[test]
    fn capabilities_key_is_rejected_forward_compat() {
        let err = parse_manifest(
            Path::new("/p/x"),
            "name=\"x\"\nversion=\"0\"\ncapabilities=[\"net\"]\n",
        )
        .unwrap_err();
        assert!(err.contains("net"), "{err}");
    }

    #[test]
    fn workspace_read_capability_is_accepted() {
        let m = parse_manifest(
            Path::new("/p/x"),
            "name=\"x\"\nversion=\"0\"\ncapabilities=[\"workspace-read\"]\n",
        )
        .unwrap();
        assert_eq!(m.capabilities, ["workspace-read"]);
    }

    #[test]
    fn phase2_surfaces_parse() {
        let m = parse_manifest(
            Path::new("/p/x"),
            r#"
name = "x"
version = "0"
formats = true
paste = true
[[inline]]
id = "e"
pattern = ":([a-z]+):"
[[decorations]]
pattern = "\\b(TODO)\\b"
style = "accent"
"#,
        )
        .unwrap();
        assert!(m.formats && m.paste);
        assert_eq!(m.inline[0].id, "e");
        assert_eq!(m.decorations[0].style, "accent");
    }

    #[test]
    fn invalid_decoration_regex_fails_discover() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("badre");
        std::fs::create_dir_all(&p).unwrap();
        std::fs::write(
            p.join("plugin.toml"),
            "name=\"badre\"\nversion=\"0\"\n[[decorations]]\npattern=\"([\"\nstyle=\"accent\"\n",
        )
        .unwrap();
        std::fs::write(p.join("plugin.wasm"), b"stub").unwrap();
        let (ok, fail) = discover(dir.path());
        assert!(ok.is_empty());
        assert_eq!(fail.len(), 1);
        assert!(fail[0].1.contains("regex") || fail[0].1.contains("pattern"), "{}", fail[0].1);
    }

    #[test]
    fn discover_collects_good_and_bad() {
        let dir = tempfile::tempdir().unwrap();
        let good = dir.path().join("good");
        std::fs::create_dir_all(&good).unwrap();
        std::fs::write(
            good.join("plugin.toml"),
            "name=\"good\"\nversion=\"1\"\nfences=[\"x\"]\n",
        )
        .unwrap();
        std::fs::write(good.join("plugin.wasm"), b"stub").unwrap();
        let bad = dir.path().join("bad");
        std::fs::create_dir_all(&bad).unwrap();
        std::fs::write(bad.join("plugin.toml"), "not toml [").unwrap();
        let (ok, fail) = discover(dir.path());
        assert_eq!(ok.len(), 1);
        assert_eq!(ok[0].name, "good");
        assert_eq!(fail.len(), 1);
    }

    #[test]
    fn discover_requires_wasm_file() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("nowasm");
        std::fs::create_dir_all(&p).unwrap();
        std::fs::write(p.join("plugin.toml"), "name=\"n\"\nversion=\"1\"\n").unwrap();
        let (ok, fail) = discover(dir.path());
        assert!(ok.is_empty());
        assert_eq!(fail.len(), 1);
        assert!(fail[0].1.contains("plugin.wasm"));
    }
}
